services:
  reveal:
    build:
      context: .
      dockerfile: Dockerfile
    image: reveal-dev
    working_dir: ${PWD}
    stdin_open: true
    tty: true

    env_file:
      - .env

    environment:
      PYTHONPATH: ${PWD}/src

    volumes:
      - type: bind
        source: ${PWD}
        target: ${PWD}

      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    extra_hosts:
      - host.docker.internal:host-gateway

    command: bash